server:
  port: 8099
spring:
  application:
    name: user-client
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-group
  redis:
    host: localhost
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: edogawaran544869
    # 配置Druid连接池参数
#    druid:
#      # 连接池配置
#      initial-size: 50 # 初始化连接数
#      min-idle: 50 # 最小空闲连接数
#      max-active: 1000 # 最大连接数
#      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒
#      time-between-eviction-runs-millis: 60000 # 间隔多久检测一次需要关闭的空闲连接，单位毫秒
#      min-evictable-idle-time-millis: 300000 # 连接在池中最小空闲时间，超过此时间的连接将被销毁，单位毫秒
#      validation-query: select 1 from dual # 校验连接是否有效的SQL语句
#      test-while-idle: true # 是否开启空闲连接检测
#      test-on-borrow: false # 是否在获取连接时检测连接的可用性
#      test-on-return: false # 是否在归还连接时检测连接的可用性
#      # 线程池配置
#      executor:
#        # 核心线程数
#        core-pool-size: 100
#        # 最大线程数
#        max-pool-size: 1000
#        # 线程空闲时间，超过这个时间没有任务执行会被回收
#        keep-alive-seconds: 300
#        # 队列长度
#        queue-capacity: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.user.user.model
  mapper-locations: classpath:mapper/*.xml
