server:
  port: 8084
spring:
  application:
    name: coupon-client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coupon?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: edogawaran544869
  kafka:
    bootstrap-servers: localhost:9092  # Kafka 服务器的地址和端口
    consumer:
      group-id: my-consumer-group  # 消费者组的唯一标识
      auto-offset-reset: earliest  # 消费者启动时的偏移重置策略
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # 键的序列化器
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # 值的序列化器
  redis:
    host: localhost   # Redis 服务器主机地址
    port: 6379        # Redis 服务器端口号
    database: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.coupon.couponserver.model
  mapper-locations: classpath:mapper/*.xml

